another test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -87,19 +87,20 @@ jobs:
         run: |
           docker info | grep Username || echo "Not logged in"
 
+      - name: Verify local image before push
+        run: |
+          docker images | grep heart-disease || echo "IMAGE NOT FOUND"
 
-      # TAG IMAGE
-      - name: Tag Docker Image
+
+     - name: Tag Docker Image
         run: |
           docker tag \
-            ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-mlflow:latest \
-            ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-mlflow:${{ github.sha }}
+            anjuans1404/heart-disease-mlflow:latest \
+            anjuans1404/heart-disease-mlflow:${{ github.sha }}
 
-
-      # PUSH IMAGE
-      - name: Tag Docker Image
+      - name: Push Docker Image
         run: |
-         docker tag \
-            ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-mlflow:latest \
-            ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-mlflow:${{ github.sha }}
+          docker push anjuans1404/heart-disease-mlflow:latest
+          docker push anjuans1404/heart-disease-mlflow:${{ github.sha }}
+
 
